Home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='Home'),  # Adicione uma rota de exemplo, como 'index'
]

equipe/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),  # Adicione uma rota de exemplo, como 'index'
    path('adicionar/', views.adicionar,name='adicionar'),
    path('criar/', views.CriarEquipe.as_view(), name='adicionar_equipe'),
    path('editar/<int:pk>/', views.EditarEquipe.as_view(), name='editar_equipe'),
    path('deletar/<int:pk>/', views.DeletarEquipe.as_view(), name='deletar_equipe'),
]

monografias/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='Home'),  
    # Adicione uma rota de exemplo, como 'index'
    path('detalhes/<int:pk>/', views.detalhes, name='detalhes'),
    path('criar/', views.CriarMonografia.as_view(), name='criar_monografia'),
    path('editar/<int:pk>/', views.EditarMonografia.as_view(), name='editar_monografia'),
    path('deletar/<int:pk>/', views.DeletarMonografia.as_view(), name='deletar_monografia'),
]

projeto1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('Home.urls')),  # Aplique include corretamente
    path('admin/', admin.site.urls),
    path('equipe/', include('equipe.urls')),
    path('monografias/', include('monografias.urls'), name='monografias'),
]

Home/models.py
from django.db import models

# Create your models here.

equipe/models.py
from django.db import models

# Create your models here.
class Equipe(models.Model):
    #nome
    nome = models.CharField(max_length=200)
    #formação academica
    fa =(
        ("G", "Graduação"),
        ("M", "Mestrado"),
        ("D", "Doutorado"),
    )

    formacao_academica = models.CharField(max_length=30, choices=fa, default='G')
    #email
    email = models.EmailField(max_length=100,null=True,blank=True)
    #data e hora de cadastro
    registro_criado = models.DateTimeField(auto_now_add=True)
    #data e hora registro atualizado
    registro_atualizado = models.DateTimeField(auto_now=True)

    #lattes = models.URLField(max_length=200,null=True,blank=True)
    #google_scholar = models.URLField(max_length=200,null=True,blank=True)
    #research_gate = models.URLField(max_length=200,null=True,blank=True)
    #linkedin = models.URLField(max_length=200,null=True,blank=True)
    #orcid = models.URLField(max_length=200,null=True,blank=True)
    #github = models.URLField(max_length=200,null=True,blank=True)


    def __str__(self):
        return self.nome

monografias/models.py
from django.db import models

from equipe.models import Equipe

# Create your models here.
class Monografias(models.Model):
    titulo = models.CharField(max_length=250)
    discente = models.OneToOneField(Equipe,on_delete=models.CASCADE)
    orientador = models.ForeignKey(Equipe,on_delete=models.CASCADE,null=True,blank=True,related_name="orientador")
    coorientador = models.ForeignKey(Equipe,on_delete=models.CASCADE,null=True,blank=True,related_name="coorientador")
    dat = models.DateTimeField(null=True,blank=True)

    def __str__(self):
        return self.titulo

templates/models.py
from django.db import models

# Create your models here.

equipe/forms.py
from django import forms
from .models import Equipe

class EquipeForm(forms.ModelForm):
    class Meta:
        model = Equipe
        fields = '__all__'

monografias/forms.py
from django import forms
from .models import Monografias
class MonografiaForm(forms.ModelForm):
    class Meta:
        model = Monografias
        fields = '__all__'

  

Home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')
  # Certifique-se de ter o template 'home.html'
def some_view(request):
    from .models import SomeModel 

equipe/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Equipe
from .forms import EquipeForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
# Create your views here.

def index(request):
    equipe = Equipe.objects.all()
    context = {
        'lista': equipe
    }
    return render(request, 'equipe.html', context)
  # Certifique-se de ter o template 'home.html'
def adicionar(request):
    if request.method == "POST":
        form = EquipeForm(request.POST)  # Passe os dados da solicitação para o formulário.
        if form.is_valid():
            post = form.save()
            post . save()
            form = EquipeForm()
            return render(request, 'adicionar_equipe.html', {'form': form})  # Fornecer o contexto adequado.
    else:
        form = EquipeForm()
    return render(request, 'adicionar_equipe.html', {'form': form})  # Certifique-se de fornecer o formulário, mesmo no ramo "else".


def some_view(request):
   from .models import SomeModel 

class CriarEquipe( CreateView):
    model = Equipe
    form_class = EquipeForm
    template_name = 'adicionar_equipe.html'
    success_url = reverse_lazy('index')

class EditarEquipe(UpdateView):
    model = Equipe
    form_class = EquipeForm
    template_name = 'editar_equipe.html'
    success_url = reverse_lazy('index')    

class DeletarEquipe(DeleteView):
    model = Equipe
    template_name = 'deletar_equipe.html'    
    success_url = reverse_lazy('index')

monografias/views.py
from datetime import date
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from monografias.forms import MonografiaForm
from . models import Monografias
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
# Create your views here.
def index(request):
    if request.method == 'POST':
        dados = request.POST.copy()
        inicio = int(dados('ano_inicial'))
        fim = int(dados('ano_final'))
        monografias = Monografias.objects.filter(dat_range=(date(inicio,1,1), date(fim,12,31)))
    else:
        monografias = Monografias.objects.all()
    
    context = {
        'lista': monografias
    }
    return render(request, 'monografias.html', context)

def detalhes(request,pk):
    print("Primary Key {}".format(pk))
    try:
        monografias = Monografias.objects.filter(pk=pk)
        print(monografias.values())
    
    except monografias.DoesNotExist:
        raise Http404('Monografia não existe')
    
    context = {
        'monografias':monografias
    }
    return render(request,'detalhes.html',context)


class CriarMonografia( CreateView):
    model = Monografias
    form_class = MonografiaForm

    template_name = 'add_monografia.html'
    success_url = reverse_lazy('index')

class EditarMonografia(UpdateView):
    model = Monografias
    form_class = MonografiaForm
    template_name = 'edit_monografia.html'
    success_url = reverse_lazy('index')

class DeletarMonografia(DeleteView):
    model = Monografias
    template_name = 'delete_monografia.html'
    success_url = reverse_lazy('index')

templates/views.py
from django.shortcuts import render

# Create your views here.

Home/templates/index.html
{% extends 'base.html' %}
{% block content %}

    <h1>Home</h1>

{% endblock %}

equipe/templates/adicionar_equipe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Criar usuario{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Adicionar</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Criar</button>
        <a class="btn btn-light" href="/">Voltar</a>
    </form>
   
</div>
{% endblock %}

equipe/templates/deletar_equipe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Excluir Usuario{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Excluir usuario</h2>
    <p>Você tem certeza que deseja excluir este usuario?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar Exclusão</button>
        <a class="btn btn-light" href="{% url 'index' %}">Voltar</a>
    </form>
</div>
{% endblock %}

equipe/templates/editar_equipe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Editar usuario{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Editar usuario</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Salvar</button>
        <a class="btn btn-light" href="{% url 'index' %}">Voltar</a>
    </form>
</div>
{% endblock %}

equipe/templates/equipe.html
{% extends 'base.html' %}
{% block content %}

    <h1>Equipe</h1>
<table class="table">
    <thead>
      <tr>
        <th scope=>Nome</th>
        <th scope=>Formação Academica</th>
        <th scope=>Email</th>
      </tr>
    </thead>
    <tbody>
        {% for e in lista %}
      <tr>
        <td>{{e.nome}}</td>
        <td>{{e.get_formacao_academica_display}}</td>
        <td>{{e.email}}</td>
        <td>
          <a href="{% url 'editar_equipe' pk=e.pk %}" class="btn btn-warning btn-sm">Editar</a>
          <a href="{% url 'deletar_equipe' pk=e.pk %}" class="btn btn-danger btn-sm">Excluir</a>
      </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endblock %}

monografias/templates/add_monografia.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Criar Monografia{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Criar Monografia</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Criar</button>
        <a class="btn btn-light" href="/">Voltar</a>
    </form>
   
</div>
{% endblock %}

monografias/templates/delete_monografia.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Excluir Monografia{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Excluir Monografia</h2>
    <p>Você tem certeza que deseja excluir esta monografia?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar Exclusão</button>
        <a class="btn btn-light" href="{% url 'index' %}">Voltar</a>
    </form>
</div>
{% endblock %}

monografias/templates/detalhes.html
{% extends 'base.html' %}
{% block content %}

    <h1>Monografias/Detalhes</h1>
    {% for e in monografias %}
    <ul>
            <li>{{item.titulo}}</li>
            <li>{{item.discente}}</li>
            <li>{{item.orientador}}</li>
            <li>{{item.coorientador}}</li>
            <li>{{item.dat}}</li>
    </ul>
    {% endfor %}


{% endblock %}

monografias/templates/edit_monografia.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Editar Monografia{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Editar Monografia</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Salvar</button>
        <a class="btn btn-light" href="{% url 'index' %}">Voltar</a>
    </form>
</div>
{% endblock %}

monografias/templates/monografias.html
{% extends 'base.html' %}
{% block content %}

    <h1>Monografias</h1>
    <p>Valor {{valor}}</p>
    <form action="" method="post" nome="formulario">
      {% csrf_token %}
      <label for="inicial">Ano Inicial:</label>
        <select name="ano_inicial" id="inicial">
          <option value="2006" selected="selected">2006</option>
          <option value="2007">2007</option>
          <option value="2008">2008</option>
          <option value="2009">2009</option>
          <option value="2010">2010</option>
          <option value="2011">2011</option>
          <option value="2012">2012</option>
          <option value="2013">2013</option>
          <option value="2014">2014</option>
          <option value="2015">2016</option>
          <option value="2017">2017</option>
          <option value="2018">2018</option>
          <option value="2019">2019</option>
        </select>

      <label for="final">Ano Final:</label>
          <select name="ano_final" id="final">
          <option value="2006">2006</option>
          <option value="2007">2007</option>
          <option value="2008">2008</option>
          <option value="2009">2009</option>
          <option value="2010">2010</option>
          <option value="2011">2011</option>
          <option value="2012">2012</option>
          <option value="2013">2013</option>
          <option value="2014">2014</option>
          <option value="2015">2016</option>
          <option value="2017">2017</option>
          <option value="2018">2018</option>
          <option value="2019" selected="selected">2019</option>
        </select>
      <input triy="submit" value="ok">

    </form>
      


    <table class="table">
        <thead>
          <tr>
            <th scope=>Titulo</th>
            <th scope=>Discente</th>
            <th scope=>Orientador</th>
            <th scope=>Coorientador</th>
            <th scope=>Ano</th>
         </tr>
        </thead>
        <tbody>
            {% for e in lista %}
          <tr>
            <td><a href="{% url 'detalhes' pk=e.pk %}"> {{e.titulo}} </a></td>
            <td>{{e.discente}}</td>
            <td>{{e.orientador}}</td>
            <td>{{e.coorientador}}</td>
            <td>{{e.dat}}</td>
            <td>
              <a href="{% url 'editar_monografia' pk=e.pk %}" class="btn btn-warning btn-sm">Editar</a>
              <a href="{% url 'deletar_monografia' pk=e.pk %}" class="btn btn-danger btn-sm">Excluir</a>
          </td>
          </tr>
          <tr>
           
          {% endfor %}
        </tbody>
      </table>
    

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <title>Document</title>
    <style>
        footer{
            background-color: rgb(56, 56, 56);
            color: white;
            text-align: center;
        }
    </style>
</head>
<body>
    <header>
        {% include "navbar.html" %}
    </header>
    {% block content %}

    {% endblock %}

    <footer>
        <p>Criado por alunos da UFVJM</p>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="tipoDispositivo">Tipo de dispositivos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/adicionar/">adicionar_equipe</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'criar_monografia' %}">Criar Monografia</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="/monografias/">Monografias</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/equipe">Equipes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url  'adicionar_equipe' %}">Adicionar Equipe</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>